version: '3.1'

services:
  db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${DB_DATABASE:-database}'
      MYSQL_USER: '${DB_USERNAME:-username}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"

volumes:
  db:
